language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

addons:
  code_climate:
    repo_token: 3c5acb08f5e2f697ef1a32758bd2e3d0f3801a3daf2fa91d4d72ffb37580ef94

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install

install:
  - composer require satooshi/php-coveralls:~1.0

script:
  - phpunit --configuration phpunit.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
